# services/finance_agent.py
"""
LangGraph Finance Intelligence Agent

This is a STATE MACHINE that orchestrates multiple
AI operations to produce deep financial analysis.

GRAPH FLOW:
START
  ↓
fetch_data (get transactions from DB)
  ↓
analyze_spending (find patterns)
  ↓
check_health (is user's finance healthy?)
  ↓
  ├── "healthy" → generate_positive_report
  └── "needs_attention" → generate_alert_report
                ↓
        format_output
                ↓
              END
"""

# ─────────────────────────────────────────────────────
# IMPORTS
# ─────────────────────────────────────────────────────

import os
from typing import TypedDict, List, Dict, Optional, Annotated
# TypedDict = define dictionary structure with types
#             Like TypeScript interfaces but for Python!
# List = type hint for lists
# Dict = type hint for dicts
# Optional = can be None
# Annotated = add metadata to types (used by LangGraph)

from langgraph.graph import StateGraph, END
# StateGraph = the main graph class
#              We add nodes and edges to this
# END = special constant meaning "stop the graph"
#       When an edge points to END, graph finishes

from langchain_google_genai import ChatGoogleGenerativeAI
# Our Gemini AI model
# Same one we used before!

from dotenv import load_dotenv
load_dotenv()
# Load .env file so GEMINI_API_KEY is available


# ─────────────────────────────────────────────────────
# SETUP GEMINI
# ─────────────────────────────────────────────────────

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.7,
)
# Same as before - our AI model
# Created once, reused by all nodes


# ─────────────────────────────────────────────────────
# STATE DEFINITION
# This is the "memory" of our graph
# Every node reads from and writes to this
# ─────────────────────────────────────────────────────

class FinanceState(TypedDict):
    """
    The state that flows through our graph
    
    Think of it like a "work order" in a factory:
    - Starts mostly empty at the beginning
    - Each node fills in its part
    - By the end, everything is filled in
    
    LIKE TYPESCRIPT:
    interface FinanceState {
        user_id: string;
        transactions: Transaction[];
        summary: Summary;
        spending_analysis: string;
        financial_health: string;
        report: string;
        alert_message: string;
        final_output: string;
        error: string | null;
    }
    """
    
    user_id: str
    # ↑ Who we're analyzing
    #   Set at the START by the caller
    #   Never changes during graph execution
    
    transactions: List[Dict]
    # ↑ List of transaction dicts from database
    #   Set by: fetch_data node
    #   Read by: analyze_spending node
    
    summary: Dict
    # ↑ Financial summary (income, expense, balance)
    #   Set by: fetch_data node
    #   Read by: analyze_spending, check_health nodes
    
    spending_analysis: str
    # ↑ AI's analysis of spending patterns
    #   Set by: analyze_spending node
    #   Read by: check_health, generate report nodes
    
    financial_health: str
    # ↑ "healthy" or "needs_attention"
    #   Set by: check_health node
    #   Read by: conditional edge router
    #   This determines which path graph takes!
    
    report: str
    # ↑ The detailed report generated by AI
    #   Set by: generate_positive_report OR generate_alert_report
    #   Read by: format_output node
    
    alert_message: str
    # ↑ Warning message if finances need attention
    #   Set by: generate_alert_report node
    #   Empty string if finances are healthy
    
    final_output: str
    # ↑ The final formatted response
    #   Set by: format_output node
    #   This is what we return to the API endpoint!
    
    error: Optional[str]
    # ↑ Error message if something goes wrong
    #   None = no error
    #   "some error" = something failed


# ─────────────────────────────────────────────────────
# HELPER: Format transactions for AI
# ─────────────────────────────────────────────────────

def format_transactions(transactions: List[Dict]) -> str:
    """
    Convert list of transaction dicts to readable text
    
    WHY?
    AI understands text, not Python dicts
    We convert once here, reuse everywhere
    
    INPUT:
    [
        {"type": "expense", "category": "Food", "amount": 500},
        {"type": "income", "category": "Salary", "amount": 5000}
    ]
    
    OUTPUT:
    "- EXPENSE: Food - $500.00
     - INCOME: Salary - $5000.00"
    """
    if not transactions:
        return "No transactions found"
    
    lines = []
    for t in transactions:
        line = (
            f"- {t.get('type', 'unknown').upper()}: "
            f"{t.get('category', 'Unknown')} "
            f"- ${float(t.get('amount', 0)):.2f}"
        )
        # .get('type', 'unknown') = get 'type' or 'unknown' if missing
        # .upper() = EXPENSE not expense
        # :.2f = 500.00 not 500
        lines.append(line)
    
    return "\n".join(lines)
    # "\n".join = put each on its own line


# ─────────────────────────────────────────────────────
# NODE 1: fetch_data
# Gets user's financial data from database
# ─────────────────────────────────────────────────────

def fetch_data(state: FinanceState) -> FinanceState:
    """
    NODE 1: Fetch transactions and summary from database
    
    INPUT STATE:
    { user_id: "abc-123", ... (rest empty) }
    
    OUTPUT STATE:
    { 
        user_id: "abc-123",
        transactions: [...],   ← ADDED
        summary: {...},        ← ADDED
        ...
    }
    
    WHY SEPARATE NODE?
    Single responsibility principle
    Easy to test independently
    Easy to replace with different data source
    """
    
    try:
        # Import here to avoid circular imports
        import database
        from db import SessionLocal
        # ↑ We create our own DB session here
        #   Can't use Depends() outside FastAPI
        #   So we create session manually
        
        db = SessionLocal()
        # ↑ Create database connection
        
        user_id = state["user_id"]
        # ↑ Read user_id from state
        #   This was set when graph was invoked
        
        # Get transactions for this user
        transactions = database.get_all_transactions(
            db,
            user_id=user_id
        )
        # ↑ Same function we use in our API!
        #   Returns list of transaction dicts
        #   Filtered by user_id (only their data)
        
        # Get financial summary
        summary = database.get_summary(
            db,
            user_id=user_id
        )
        # ↑ Returns {total_income, total_expense, balance, count}
        
        db.close()
        # ↑ ALWAYS close database connection!
        #   Otherwise connection leak!
        
        # Return updated state
        return {
            **state,
            # ↑ Spread operator = copy ALL existing state
            #   Same as {...state} in JavaScript
            #   Keeps user_id and everything else
            
            "transactions": transactions,
            # ↑ Add transactions to state
            
            "summary": summary,
            # ↑ Add summary to state
            
            "error": None
            # ↑ No error = success
        }
    
    except Exception as e:
        # If database fails, record error in state
        return {
            **state,
            "transactions": [],
            "summary": {},
            "error": f"Failed to fetch data: {str(e)}"
        }
        # ↑ Don't crash the whole graph!
        #   Set error in state
        #   Other nodes can check for errors


# ─────────────────────────────────────────────────────
# NODE 2: analyze_spending
# AI analyzes spending patterns
# ─────────────────────────────────────────────────────

def analyze_spending(state: FinanceState) -> FinanceState:
    """
    NODE 2: Use Gemini to analyze spending patterns
    
    INPUT STATE:
    { transactions: [...], summary: {...}, ... }
    
    OUTPUT STATE:
    { spending_analysis: "...", ... }  ← ADDED
    
    This is where AI does the heavy lifting!
    """
    
    # Check if previous node had error
    if state.get("error"):
        return state
        # ↑ If fetch_data failed, skip this node
        #   Propagate error to end of graph
        #   Don't try to analyze empty data!
    
    # Check if there's data to analyze
    if not state["transactions"]:
        return {
            **state,
            "spending_analysis": "No transactions found to analyze.",
            "error": None
        }
    
    # Format data for AI
    transactions_text = format_transactions(state["transactions"])
    summary = state["summary"]
    
    # Build detailed analysis prompt
    prompt = f"""You are a personal finance expert analyzing a user's spending data.

FINANCIAL SUMMARY:
- Total Income: ${summary.get('total_income', 0):.2f}
- Total Expenses: ${summary.get('total_expense', 0):.2f}
- Current Balance: ${summary.get('balance', 0):.2f}
- Number of Transactions: {summary.get('transaction_count', 0)}

ALL TRANSACTIONS:
{transactions_text}

Please provide a DETAILED analysis covering:

1. SPENDING BREAKDOWN
   - Which categories have highest spending?
   - What percentage of income goes to each category?

2. PATTERNS & TRENDS
   - Any unusual spending patterns?
   - Recurring expenses identified?
   - One-time vs regular expenses?

3. INCOME VS EXPENSE RATIO
   - What percentage of income is being spent?
   - Is the savings rate healthy?

4. RED FLAGS
   - Any concerning spending patterns?
   - Categories where spending seems excessive?

Be specific and use the actual numbers provided.
Keep analysis under 400 words.
Format with clear sections."""
    
    # Call Gemini AI
    response = llm.invoke(prompt)
    # ↑ Send prompt to Gemini
    #   Returns AIMessage object
    #   .content = the actual text
    
    analysis = response.content
    # ↑ Extract text from response
    
    # Return updated state with analysis
    return {
        **state,
        "spending_analysis": analysis,
        # ↑ Add analysis to state
        #   Next nodes will read this
    }


# ─────────────────────────────────────────────────────
# NODE 3: check_health
# Determines if finances are healthy or need attention
# ─────────────────────────────────────────────────────

def check_health(state: FinanceState) -> FinanceState:
    """
    NODE 3: Check financial health
    
    INPUT STATE:
    { summary: {...}, spending_analysis: "...", ... }
    
    OUTPUT STATE:
    { financial_health: "healthy" OR "needs_attention", ... }
    
    WHY THIS NODE?
    This sets "financial_health" which is used by
    the CONDITIONAL EDGE to decide which path to take!
    
    "healthy" → generate_positive_report
    "needs_attention" → generate_alert_report
    """
    
    if state.get("error"):
        return state
    
    summary = state["summary"]
    
    # Calculate health metrics
    total_income = summary.get("total_income", 0)
    total_expense = summary.get("total_expense", 0)
    balance = summary.get("balance", 0)
    
    # Determine health based on simple rules
    if total_income == 0:
        # No income recorded
        health = "needs_attention"
    
    elif total_expense > total_income:
        # Spending more than earning!
        health = "needs_attention"
    
    elif total_expense > (total_income * 0.9):
        # Spending more than 90% of income
        # Less than 10% savings rate
        health = "needs_attention"
    
    else:
        # Spending less than 90% of income
        # Savings rate > 10% = healthy!
        health = "healthy"
    
    # Also ask AI to confirm health assessment
    if total_income > 0:
        savings_rate = ((total_income - total_expense) / total_income) * 100
        # ↑ What % of income is saved
        # (income - expense) / income * 100
        # e.g. (5000 - 3500) / 5000 * 100 = 30% savings rate
    else:
        savings_rate = 0
    
    return {
        **state,
        "financial_health": health,
        # ↑ "healthy" or "needs_attention"
        #   This is READ by the conditional edge!
        
        "spending_analysis": state["spending_analysis"] + 
        f"\n\n📊 SAVINGS RATE: {savings_rate:.1f}%"
        # ↑ Add savings rate to existing analysis
        #   Append don't replace!
    }


# ─────────────────────────────────────────────────────
# NODE 4A: generate_positive_report
# For healthy finances - encouraging report
# ─────────────────────────────────────────────────────

def generate_positive_report(state: FinanceState) -> FinanceState:
    """
    NODE 4A: Generate encouraging report for healthy finances
    
    REACHED WHEN: financial_health == "healthy"
    
    INPUT STATE:
    { spending_analysis: "...", summary: {...}, ... }
    
    OUTPUT STATE:
    { report: "...", alert_message: "", ... }
    """
    
    if state.get("error"):
        return state
    
    summary = state["summary"]
    analysis = state["spending_analysis"]
    
    prompt = f"""Based on this financial analysis, write an encouraging 
and detailed report for a user with HEALTHY finances.

ANALYSIS:
{analysis}

SUMMARY:
- Income: ${summary.get('total_income', 0):.2f}
- Expenses: ${summary.get('total_expense', 0):.2f}
- Balance: ${summary.get('balance', 0):.2f}

Write a report that:
1. ✅ Celebrates what they're doing well
2. 💡 Gives 3 specific tips to optimize further
3. 🎯 Suggests a savings goal based on their income
4. 📈 Recommends next financial steps

Be encouraging, specific, and use their actual numbers.
Keep under 300 words."""
    
    response = llm.invoke(prompt)
    
    return {
        **state,
        "report": response.content,
        "alert_message": ""
        # ↑ No alert for healthy finances
    }


# ─────────────────────────────────────────────────────
# NODE 4B: generate_alert_report
# For finances that need attention - helpful but urgent
# ─────────────────────────────────────────────────────

def generate_alert_report(state: FinanceState) -> FinanceState:
    """
    NODE 4B: Generate alert report for finances needing attention
    
    REACHED WHEN: financial_health == "needs_attention"
    
    Same input/output structure as generate_positive_report
    BUT generates different (more urgent) content
    """
    
    if state.get("error"):
        return state
    
    summary = state["summary"]
    analysis = state["spending_analysis"]
    
    prompt = f"""Based on this financial analysis, write a HELPFUL but URGENT 
report for a user whose finances need attention.

ANALYSIS:
{analysis}

SUMMARY:
- Income: ${summary.get('total_income', 0):.2f}
- Expenses: ${summary.get('total_expense', 0):.2f}
- Balance: ${summary.get('balance', 0):.2f}

Write a report that:
1. ⚠️ Clearly identifies the main problem
2. 🔴 Shows exactly where they're overspending
3. 💡 Gives 3 IMMEDIATE actions they can take
4. 📉 Shows how much they need to cut to be healthy
5. 🎯 Sets a realistic 30-day improvement goal

Be helpful not harsh. Use their actual numbers.
Keep under 300 words."""
    
    response = llm.invoke(prompt)
    
    # Generate a short alert message
    alert_prompt = f"""In ONE sentence, write an urgent but caring alert 
for someone spending more than they earn.
Their balance is ${summary.get('balance', 0):.2f}.
Start with an emoji."""
    
    alert_response = llm.invoke(alert_prompt)
    
    return {
        **state,
        "report": response.content,
        "alert_message": alert_response.content
        # ↑ Alert message for frontend to show prominently
    }


# ─────────────────────────────────────────────────────
# NODE 5: format_output
# Combines everything into final beautiful response
# ─────────────────────────────────────────────────────

def format_output(state: FinanceState) -> FinanceState:
    """
    NODE 5: Format everything into final output
    
    This is the LAST node before END
    Combines analysis + report into one clean response
    
    INPUT STATE:
    { spending_analysis: "...", report: "...", 
      alert_message: "...", financial_health: "...", ... }
    
    OUTPUT STATE:
    { final_output: "complete formatted response", ... }
    """
    
    if state.get("error"):
        return {
            **state,
            "final_output": f"Analysis failed: {state['error']}"
        }
    
    health = state.get("financial_health", "unknown")
    analysis = state.get("spending_analysis", "")
    report = state.get("report", "")
    alert = state.get("alert_message", "")
    summary = state.get("summary", {})
    
    # Build the final formatted output
    health_emoji = "✅" if health == "healthy" else "⚠️"
    health_label = "HEALTHY" if health == "healthy" else "NEEDS ATTENTION"
    
    final = f"""
{health_emoji} FINANCIAL HEALTH STATUS: {health_label}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💰 QUICK SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Income:   ${summary.get('total_income', 0):.2f}
Expenses: ${summary.get('total_expense', 0):.2f}
Balance:  ${summary.get('balance', 0):.2f}
Transactions: {summary.get('transaction_count', 0)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔍 SPENDING ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{analysis}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 DETAILED REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{report}
""".strip()
    # .strip() removes leading/trailing whitespace
    
    # Add alert if needed
    if alert:
        final = f"🚨 ALERT: {alert}\n\n" + final
        # ↑ Put alert at TOP so user sees it first!
    
    return {
        **state,
        "final_output": final
        # ↑ This is what the API endpoint returns!
    }


# ─────────────────────────────────────────────────────
# ROUTER FUNCTION
# Decides which node to go to after check_health
# ─────────────────────────────────────────────────────

def route_by_health(state: FinanceState) -> str:
    """
    ROUTER: Decides next node based on financial health
    
    Called by conditional edge after check_health node
    
    Returns a STRING that maps to a node name
    
    LIKE A SWITCH STATEMENT:
    switch(state.financial_health) {
        case "healthy": return "generate_positive_report"
        case "needs_attention": return "generate_alert_report"
        default: return "generate_alert_report"
    }
    """
    
    if state.get("error"):
        return "format_output"
        # ↑ If there's an error, skip to format_output
        #   format_output handles errors gracefully
    
    health = state.get("financial_health", "needs_attention")
    
    if health == "healthy":
        return "generate_positive_report"
        # ↑ String must EXACTLY match node name added with add_node()
    else:
        return "generate_alert_report"


# ─────────────────────────────────────────────────────
# BUILD THE GRAPH
# Connect all nodes with edges
# ─────────────────────────────────────────────────────

def build_finance_graph():
    """
    Assembles all nodes into a complete graph
    
    Called once at startup
    Returns compiled graph ready to run
    
    LIKE BUILDING A FLOWCHART:
    1. Create blank flowchart (StateGraph)
    2. Add boxes (add_node)
    3. Draw arrows (add_edge)
    4. Draw conditional arrows (add_conditional_edges)
    5. Mark start box (set_entry_point)
    6. Print flowchart (compile)
    """
    
    # Step 1: Create graph with our state type
    graph = StateGraph(FinanceState)
    # ↑ FinanceState tells graph what data to expect
    #   Like TypeScript generics: StateGraph<FinanceState>
    
    # Step 2: Add all nodes
    graph.add_node("fetch_data", fetch_data)
    # ↑ "fetch_data" = name of node (used in edges)
    #   fetch_data = the Python function to run
    
    graph.add_node("analyze_spending", analyze_spending)
    graph.add_node("check_health", check_health)
    graph.add_node("generate_positive_report", generate_positive_report)
    graph.add_node("generate_alert_report", generate_alert_report)
    graph.add_node("format_output", format_output)
    
    # Step 3: Add simple edges (always go this way)
    graph.add_edge("fetch_data", "analyze_spending")
    # ↑ After fetch_data ALWAYS go to analyze_spending
    #   No conditions, always this path
    
    graph.add_edge("analyze_spending", "check_health")
    # ↑ After analyze_spending ALWAYS go to check_health
    
    # Step 4: Add conditional edge (go different ways)
    graph.add_conditional_edges(
        "check_health",
        # ↑ FROM this node...
        
        route_by_health,
        # ↑ Call this function to decide where to go
        #   Function returns a string (node name)
        
        {
            "generate_positive_report": "generate_positive_report",
            "generate_alert_report": "generate_alert_report",
            "format_output": "format_output"
            # ↑ Map return values to node names
            #   Key = what route_by_health returns
            #   Value = which node to go to
        }
    )
    # ↑ This creates the FORK in the graph:
    #   check_health → route_by_health() → one of two paths
    
    # Step 5: Both report nodes go to format_output
    graph.add_edge("generate_positive_report", "format_output")
    graph.add_edge("generate_alert_report", "format_output")
    # ↑ Both paths MERGE back here
    #   Like two lanes merging on a highway
    
    # Step 6: format_output goes to END
    graph.add_edge("format_output", END)
    # ↑ END is special - means graph is done
    #   No more nodes to run
    
    # Step 7: Set where graph starts
    graph.set_entry_point("fetch_data")
    # ↑ First node to run when graph.invoke() is called
    
    # Step 8: Compile the graph
    compiled = graph.compile()
    # ↑ Validates the graph (checks for missing nodes etc)
    #   Returns runnable graph object
    #   Like "building" a React app - validates everything
    
    return compiled


# ─────────────────────────────────────────────────────
# CREATE GRAPH INSTANCE
# Built once when file is imported
# ─────────────────────────────────────────────────────

finance_graph = build_finance_graph()
# ↑ Create the graph ONE TIME when file loads
#   Reuse for every request (more efficient!)
#   Like creating axios instance once and reusing


# ─────────────────────────────────────────────────────
# MAIN FUNCTION
# Called by API endpoint
# ─────────────────────────────────────────────────────

def run_finance_analysis(user_id: str) -> dict:
    """
    Run the complete finance analysis graph for a user
    
    CALLED BY:
    GET /ai/deep-analysis endpoint
    
    ARGS:
    user_id: The user's UUID from JWT token
    
    RETURNS:
    {
        "final_output": "complete analysis text",
        "financial_health": "healthy" or "needs_attention",
        "alert_message": "" or "urgent message",
        "summary": {...}
    }
    """
    
    # Initial state - mostly empty
    # Each node fills in its part
    initial_state: FinanceState = {
        "user_id": user_id,
        # ↑ Only this is set at the start
        
        "transactions": [],
        "summary": {},
        "spending_analysis": "",
        "financial_health": "",
        "report": "",
        "alert_message": "",
        "final_output": "",
        "error": None
        # ↑ Everything else starts empty
        #   Nodes will fill these in as graph runs
    }
    
    # Run the graph!
    result = finance_graph.invoke(initial_state)
    # ↑ This triggers the entire graph:
    #   fetch_data → analyze_spending → check_health
    #   → generate_positive/alert_report → format_output
    #
    # invoke() BLOCKS until graph completes
    # (synchronous - waits for all nodes)
    #
    # result = final state after all nodes ran
    
    # Return what the API endpoint needs
    return {
        "final_output": result.get("final_output", "Analysis failed"),
        "financial_health": result.get("financial_health", "unknown"),
        "alert_message": result.get("alert_message", ""),
        "summary": result.get("summary", {}),
        "error": result.get("error")
    }